### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by zertosh**
@sebmck I'll take this repo off your hands if you want :stuck_out_tongue:

### CODE REVIEW

**Comment by zertosh** [comment]
I don't know what goes into setting up travis, but please set it up

**Comment by sebmck** [comment]
> I'll take this repo off your hands if you want :stuck_out_tongue:

Yesss. Added you as as an npm owner and enabled travis. Thanks!

**Comment by zertosh** [comment]
Thanks @sebmck! I'm not a collaborator here - I think I only have privileges for babel-sublime.

**Comment by sebmck** [comment]
Oh right, whoops. I forgot GitHub permissions were a thing.

**Comment by zertosh** [comment]
There it is, thanks!

**Comment by zertosh** [comment]
Published as babelify@6.1.0

**Pull request merged**
