### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ivanoats**
Update babel-core, lodash, and through dependencies

### CODE REVIEW

**Comment by ivanoats** [comment]
I realized this isn't totally necessary because of ^ but it was easier to get latest versions this way.

**Comment by mtomcal** [comment]
It is necessary to update this package to use the new transforms like "runtime". I am currently using "selfContained" which is the same thing but it was confusing for awhile why that transform didnt work with babelify.

**Comment by sebmck** [comment]
@ivanoats You can just reinstall `babelify` and you get the latest.

@mtomcal The `selfContained` transformer is implemented as an alias to `runtime` so it should work?

```sh
$ babel --optional selfContained
The transformer selfContained has been renamed to runtime
```

**Comment by mtomcal** [comment]
@sebmck As I was fiddling with my package.json it looks like it started to work after getting babel itself upgraded. Thanks for looking into to this though.

**Pull request closed without merging**
