### PR TITLE
Upgrade to Babel 7 and @babel scoped packages

### LINKED ISSUE #231: [7.0] babel.util.arrayify and babel.util.canCompile are being removed
Currently https://github.com/babel/babel/pull/5487 is proposing the removal of the whole `babel.util` object.

The extensions are now exposed at `babel.DEFAULT_EXTENSIONS`, `canCompile` was very simple, and `extensions` can just be splitting on a comma, so it should be a very easy update for 7.x.

### LINKED ISSUE #251: Using babelify with new scoped packages
Today I installed the new scoped packages of babel, e.g. `@babel/core` etc., including the plugins, e.g. `@babel/plugin-proposal-pipeline-operator` etc. However, `babelify@8` still requires the 'old' `babel-core` package, AFAICT. I first installed `babel-core@6` by accident, which had problems with the new `.babelrc` plugin syntax (before it would prefix `babel-plugin-` to get the package, I think; now it'd need to add `plugin-` between `@babel/` and the plugin name).

However, `babel-core@7.0.0-beta.3`, the latest I could find, gave the following error instead:

```
/home/larsw/project_dir/node_modules/babelify/index.js:65
  if (!babel.util.canCompile(filename, extensions)) {
                  ^

TypeError: Cannot read property 'canCompile' of undefined
  at /home/larsw/project_dir/node_modules/babelify/index.js:65:21
  at Babelify (/home/larsw/project_dir/node_modules/babelify/index.js:10:36)
  at nr (/home/larsw/project_dir/node_modules/module-deps/index.js:301:23)
  at onfile (/home/larsw/project_dir/node_modules/resolve/lib/async.js:56:21)
  at onex (/home/larsw/project_dir/node_modules/resolve/lib/async.js:104:32)
  at /home/larsw/project_dir/node_modules/resolve/lib/async.js:24:24
  at FSReqWrap.oncomplete (fs.js:153:5)
```

Note: I'm not sure if it's possible to use babelify with the new scoped packages at all.

### LINKED ISSUE #254: Unknown option: direct.presets while parsing file. babel7, babelify8, browserify14
Hi there, im getting mad at this error. Please advice: what could cause the error? how to avoid it? Should i simply downgrade everything?

This is my devDepandencies object in package.json: 
{
    "@babel/cli": "^7.0.0-beta",
    "@babel/core": "^7.0.0-beta",
    "@babel/preset-env": "^7.0.0-beta",
    "@babel/preset-es2015": "^7.0.0-beta",
    "@babel/preset-es2016": "^7.0.0-beta",
    "@babel/preset-es2017": "^7.0.0-beta",
    "@babel/preset-flow": "^7.0.0-beta",
    "@babel/preset-stage-2": "^7.0.0-beta",
    "@babel/preset-stage-3": "^7.0.0-beta",
    "@babel/register": "^7.0.0",
    "babelify": "^8.0.0",
    "browserify": "^14.5.0",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-autoprefixer": "3.1.0",
    "gulp-babel": "^7.0.0",
    "gulp-batch": "1.0.5",
    "gulp-buffer": "0.0.2",
    "gulp-cli": "github:gulpjs/gulp-cli",
    "gulp-filter": "3.0.1",
    "gulp-plumber": "1.0.1",
    "gulp-postcss": "6.3.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "2.2.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "1.5.2",
    "gulp-using": "0.1.0",
    "gulp-util": "3.0.7",
    "gulp-watch": "4.3.11",
    "vinyl-source-stream": "^1.1.0"
  }

### PR DESCRIPTION
**Pull request by ylemkimon**
- Change dependencies/`require` to use @babel scoped packages
- Use asynchronous `babel.transform`
- Replace removed functions/properties: `babel.util.arrayify`, `babel.util.canCompile`, `result.metadata.usedHelpers`
- Even without `sourceFileName`, Babel 7 maps source files to absolute path, if `sourceMapsAbsolute` is false(default), set `sourceFileName` to its base name
- Updated test cases

Fixes #254, fixes #251, fixes #231

### CODE REVIEW

**Comment by vcarel** [comment]
Hi, can this PR be merged? What about the unit test mentioned above?

**Comment by ylemkimon** [comment]
@vcarel This PR can be merged without any problems, but the tests will not cover error emission.

**Comment by julien-f** [comment]
Would it be difficult to keep the compatibility with Babel 6 and support Babel 7 through `babel-core@bridge`?

**Comment by loganfsmyth** [comment]
@julien-f Generally me and the Babel team have been recommending against using the bridge unless you really are in a place where you have to support multiple versions via one package, but using gulp-babel doesn't seem like a case where that is likely to be needed.

**Comment by julien-f** [comment]
Makes sense, thanks :)

**Comment by krazyjakee** [comment]
@ylemkimon Great PR but I can't seem to get your version to compile without throwing the `ParseError: 'import' and 'export' may appear only with 'sourceType: module'` error. There's no reason this shouldn't work while [browserify has 7x version of @babel/preset-env set as a preset](https://github.com/Keyframes/Keyframes.Pathfinder/blob/master/package.json#L9).

Check this out: https://github.com/Keyframes/Keyframes.Pathfinder
Clone and run `npm install && npm run build`

**Comment by Hoten** [comment]
Can a beta be released?

**Comment by goto-bus-stop** [comment]
I think we can replace `babel-plugin-undeclared-variables-check` in test/error.js with something else that throws an error. Maybe `@babel/plugin-transform-classes` with a snippet like this?

```js
class A {
  // calling super() w/o a superclass
  constructor () { super() }
}
```

**Comment by ylemkimon** [comment]
@krazyjakee Sorry for late response. You don't have to transpile the file(`npm run es6`). That's what `babelify` does do, and you can and must pass ES6 Javascript file `browserify` with `babelify`.

**Comment by ylemkimon** [comment]
@goto-bus-stop Thank you for the idea! Actually, this revealed a bug which calls callback, even if transform has failed.

**Comment by ylemkimon** [comment]
@vcarel @Hoten Now it's ready to be merged or published.

**Comment by clubajax** [comment]
I'm using ylemkimon's fork and it's working.
`"babelify": "github:ylemkimon/babelify"`

**Comment by clarcharr** [comment]
Any plans to merge this soon?

**Comment by chaines** [comment]
Not a huge fan of using a fork. Any chance this can be merged?

**Comment by futagoza** [comment]
@hzoo Any plans to merge this?

@ylemkimon This should also close the previous related PR's: #241, #242, #244, #252

**Comment by hzoo** [comment]
Sorry for delay, yeah I wasn't watching this repo actually!

We should update the readme too (doesn't have to be in this PR)

**Comment by chrisgervang** [comment]
Thank you so much for approving! I'm looking forward to using this. Can someone merge and release a beta? Much appreciated!

**Comment by hzoo** [comment]
We had a question in https://github.com/babel/babelify/pull/255#discussion_r179866063, but to land I'll just revert that.

**Comment by hzoo** [comment]
Ok yeah need to determine if https://github.com/babel/babelify/pull/255#pullrequestreview-110196926 is a regression or not before release - makes more sense now.

**Comment by Blinnikov** [comment]
Could you release it as `alpha` if this unresolved question is so important?

**Comment by goto-bus-stop** [comment]
Hm yeah, it looks like babel-core@6 defaulted `parserOpts.sourceFileName` to `basename(opts.filename)`, whereas @babel/core@7 defaults it to just `opts.filename`.

**Comment by sqren** [comment]
@hzoo Shouldn't this this PR also have bumped the version of `babelify`?
There are currently two different versions of `babelify` `8.0.0` - one [depends on Babel 6](https://github.com/babel/babelify/blob/b06b778117617884cb14890995c8a27450dd3135/package.json), the other [on Babel 7](https://github.com/babel/babelify/blob/c5e4d40b99d18dc99091815890713e2dfd614608/package.json).
Suggestion: Bump `babelify` to 9.0.0 and publish it to npm.

Current workaround to use `babelify` with Babel 7:
```
"babelify": "git+https://git@github.com/babel/babelify.git#c5e4d4"
```

**Comment by goto-bus-stop** [comment]
@sqren please see #263, this is waiting on a new babel version to fix https://github.com/babel/babelify/pull/255#pullrequestreview-110196926

**Comment by sqren** [comment]
@goto-bus-stop Okay, thanks!

**Pull request merged**
