### PR TITLE
Breaking: drop node 0.10/0.12, add peerDep on babel-core instead of dep, drop o…

### PR DESCRIPTION
**Pull request by hzoo**
…bject-assign, add package-lock

### CODE REVIEW

**Comment by zertosh** [comment]
Thanks!

**Comment by hzoo** [comment]
You going to publish as major or I can do it later

**Comment by zertosh** [comment]
Doing it now... made another change and waiting for the build to go green

**Comment by zertosh** [comment]
published as babelify@8.0.0

**Pull request merged**
